internalName: sjd_keyboard

locales:
  en:
    name: &bundleName "Kildin Sami Keyboards"
    description: "Mobile OS keyboards for the Kildin Sami language from the Divvun group at UiT."
  nb:
    name: "Kildin Sami tastatur"
    description: "Mobiltastatur for Kildin Sami fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [sjd]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.sjd
    icon: sjd-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sjd_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.sjd
    bundleName: *bundleName
    icon:
        90: sjd-icon-small.png
        150: sjd-icon.png
  osx: *AppleID
