locales:
  en:
    name: Kildin Sami Keyboards
    description: >-
      Mobile OS keyboards for the Kildin Sami language from the Divvun group at
      UiT.
  nb:
    name: Kildinsamisk tastatur
    description: Mobiltastatur for Kildinsamisk fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2021 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
