template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 5
template_sha = "c78613bb3fe4a8c35f6719494f51fe9f4013486c"

[replacements]
__UND2C__ = "sjd"
__UNDEFINED__ = "Kildin Sami"
__UND__ = "sjd"
