template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 14
template_sha = "88118b02ff670a815625db98218a131c036be739"

[replacements]
__UND2C__ = "sjd"
__UNDEFINED__ = "Kildin Sami"
__UND__ = "sjd"
