template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 15
template_sha = "bfa9497e3e6ee6e246910a63f0b3de54aee620ca"

[replacements]
__UND2C__ = "sjd"
__UNDEFINED__ = "Kildin Sami"
__UND__ = "sjd"
